name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Env
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install pytest pytest-cov pytest-pycodestyle
          pip install -e .
    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest --cov mantle2 --cov-report=xml --pycodestyle tests/
    - name: Install deploy packages
      shell: bash -l {0}
      run: |
          pip install twine
    - name: Upload to PyPI
      shell: bash -l {0}
      run: |
          source .travis/deploy.sh
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
