name: Linux Test

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Env
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          pip install pytest pytest-cov pytest-pycodestyle
          pip install -e .
    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest --cov mantle2 tests/
        pycodestyle mantle2 tests
    - name: Upload Coverage
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) 
